### PR TITLE
Importing Discovery related code

### PR DESCRIPTION
**Pull request by Kralizek**
- Adding EMG.Extensions.DependencyInjection.ServiceModel.Discovery
- Adding EMG.Extensions.DependencyInjection.ServiceModel.DiscoveryAdapter

### CODE REVIEW

**Comment by Kralizek** [comment]
@SWallmark @Josephson199 can you check the API for these new extensions?

Here are two samples: https://github.com/Kralizek/dotnet-extensions/tree/wcf-discovery/samples/DependencyInjection

**Comment by Josephson199** [comment]
Looks really good.

**Comment by Kralizek** [comment]
@SWallmark now the system should be able to negotiate the binding among those available. Also, the user can add binding factory customizations to alter how bindings are created.

**Comment by Kralizek** [comment]
RFC @SWallmark @Josephson199 pls :)

**Comment by SWallmark** [comment]
Should we clarify these two extension methods, it's hard to tell which one is for announcement and which one is for probing without having to look at the examples or the source code

- AddDiscovery
- AddServiceDiscovery

**Comment by Kralizek** [comment]
> Should we clarify these two extension methods? It's hard to tell which one is for announcement and which one is for probing without having to look at the examples or the source code
> 
> * AddDiscovery
> * AddServiceDiscovery

good point. do you think this would work?
* AddServiceDiscovery
* AddDiscoverableService

**Pull request merged**
